### ISSUE TITLE
Program eye_detect.py exits

### ISSUE THREAD

**Issue by tinashemudavanhu** [wyager/PythonEyeDetection#1]
root@beaglebone:~/Project/PythonEyeDetection# python eye_detect.py
Xlib:  extension "RANDR" missing on display ":1".
Traceback (most recent call last):
  File "eye_detect.py", line 147, in <module>
    main()
  File "eye_detect.py", line 138, in main
    finished, iris_pic = draw(photo)
  File "eye_detect.py", line 122, in draw
    image_to_show[0:iris_circles_to_show.shape[0], 200:200+iris_circles_to_show.shape[1]] = iris_circles_to_show
ValueError: operands could not be broadcast together with shapes (240,120,3) (240,240,3)

What was the resolution of the camera you used when testing? I am testing with 320x240 and 640x480 resolutions.

**Comment by wyager** [comment]
Afraid I don't remember. It was the camera on my macbook 3+ years ago.

**Comment by tinashemudavanhu** [comment]
I managed to capture eye images at 640x480 resolution but with a lower frame rate (10fps). I want to use the images for iris recognition. I have another code already in place that only retrieves saved images and process them to form a normalize them. How can i go about it in merging it with your code? I have seen you only imported the pupil_detect in your eye_detect code, if i do the same will it be imported?

**Comment by mohanram122** [comment]
the eye_detect.py file is not working. Its showing modulenotfounderror. The import statement cv2 is not found

**Comment by 877644790** [comment]
跑不通呀
